import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { BookMarked, Compass, Plus } from 'lucide-react'
import { TripCard } from '@/components/trip-card'
import { UserMenu } from '@/components/user-menu'

export const metadata = { title: 'My Trips — Travel Lab' }

async function getTrips(userId: string) {
  return prisma.itinerary.findMany({
    where: { userId },
    orderBy: { createdAt: 'desc' },
    select: {
      id: true,
      destination: true,
      totalDays: true,
      currency: true,
      prompt: true,
      createdAt: true,
      data: true,
    },
  })
}

export default async function TripsPage() {
  const session = await getServerSession(authOptions)
  if (!session?.user) redirect('/login')

  // @ts-ignore – id added by jwt/session callbacks
  const userId: string = session.user.id
  if (!userId) redirect('/login')

  const trips = await getTrips(userId)

  return (
    <div className="flex min-h-dvh flex-col">
      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-border bg-card/90 backdrop-blur-sm">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 md:px-6">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm">
              <Compass className="size-5" aria-hidden="true" />
            </div>
            <div>
              <h1 className="text-sm font-semibold leading-tight md:text-base">
                Travel Lab{' '}
                <span className="hidden text-muted-foreground font-normal sm:inline">
                  — My Trips
                </span>
              </h1>
              <p className="text-xs text-muted-foreground">
                Your saved itineraries
              </p>
            </div>
          </div>
          <Link
            href="/app"
            className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground shadow-sm transition-opacity hover:opacity-90"
          >
            <Plus className="size-3.5" aria-hidden="true" />
            New Trip
          </Link>
          <UserMenu />
        </div>
      </header>

      <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-10 md:px-6">
        {trips.length === 0 ? (
          <EmptyState />
        ) : (
          <>
            <div className="mb-6 flex items-center gap-2">
              <BookMarked className="size-4 text-primary" aria-hidden="true" />
              <h2 className="text-base font-semibold">
                {trips.length} saved {trips.length === 1 ? 'trip' : 'trips'}
              </h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {trips.map((trip) => {
                const data = trip.data as {
                  budget?: { total?: number }
                }
                const total = data?.budget?.total ?? 0
                return (
                  <TripCard
                    key={trip.id}
                    id={trip.id}
                    destination={trip.destination}
                    totalDays={trip.totalDays}
                    currency={trip.currency}
                    prompt={trip.prompt}
                    createdAt={trip.createdAt}
                    budget={total}
                  />
                )
              })}
            </div>
          </>
        )}
      </main>

      <footer className="border-t border-border py-4 text-center text-xs text-muted-foreground">
        Travel Lab — itineraries generated by AI. Prices are estimates.
      </footer>
    </div>
  )
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center py-24 text-center">
      <div className="flex size-16 items-center justify-center rounded-2xl bg-primary/10">
        <BookMarked className="size-7 text-primary" aria-hidden="true" />
      </div>
      <h2 className="mt-5 text-lg font-semibold">No trips yet</h2>
      <p className="mt-2 max-w-xs text-sm text-muted-foreground">
        Generate your first itinerary and it will be saved here automatically.
      </p>
      <Link
        href="/app"
        className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-md transition-opacity hover:opacity-90"
      >
        <Plus className="size-4" aria-hidden="true" />
        Plan your first trip
      </Link>
    </div>
  )
}
